export enum ArticleStatus {
  RAW = 'RAW',
  NORMALIZED = 'NORMALIZED',
  AI_PROCESSING = 'AI_PROCESSING',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}